<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.8" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="8.0.0" />
    
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="8.0.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GymTracker.Application\GymTracker.Application.csproj" />
    <ProjectReference Include="..\GymTracker.Domain\GymTracker.Domain.csproj" />
    <ProjectReference Include="..\GymTracker.Common\GymTracker.Common.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="..\Resources\exercises.json" Link="Resources\exercises.json" />
  </ItemGroup>

</Project>
